### ISSUE TITLE
intermittent issues with connections and file names

### ISSUE THREAD

**Issue by David-Levinthal** [soskek/bookcorpus#12]
example:
 python3.6 download_files.py --list url_list.jsonl --out out_txts --trash-bad-count
0 files had already been saved in out_txts.
File is not a zip file                                                         |
File is not a zip file
File is not a zip file
File is not a zip file
File is not a zip file
Failed to open https://www.smashwords.com/books/download/490185/8/latest/0/0/existence.epub
HTTPError: HTTP Error 503: Service Temporarily Unavailable
Succeeded in opening https://www.smashwords.com/books/download/490185/8/latest/0/0/existence.epub
File is not a zip file
File is not a zip file                                                         |
File is not a zip file
File is not a zip file
File is not a zip file                                                         |
File is not a zip file
File is not a zip file
"There is no item named '' in the archive"
File is not a zip file
File is not a zip file
"There is no item named 'OPS/' in the archive"
File is not a zip file
File is not a zip file                                                         |
File is not a zip file
Failed to open https://www.smashwords.com/books/download/793264/8/latest/0/0/jaynells-wolf.epub
HTTPError: HTTP Error 503: Service Temporarily Unavailable
Succeeded in opening https://www.smashwords.com/books/download/793264/8/latest/0/0/jaynells-wolf.epub
Failed to open https://www.smashwords.com/books/download/479710/6/latest/0/0/tainted-ava-delaney-lost-souls-1.txt
HTTPError: HTTP Error 503: Service Temporarily Unavailable
Succeeded in opening https://www.smashwords.com/books/download/479710/6/latest/0/0/tainted-ava-delaney-lost-souls-1.txt
File is not a zip file
"There is no item named 'OPS/' in the archive"
File is not a zip file
Failed to open https://www.smashwords.com/books/download/496160/8/latest/0/0/royal-blood-royal-blood-1.epub
HTTPError: HTTP Error 404: Not Found
Failed to open https://www.smashwords.com/books/download/496160/8/latest/0/0/royal-blood-royal-blood-1.epub
HTTPError: HTTP Error 404: Not Found
 Gave up to open https://www.smashwords.com/books/download/496160/8/latest/0/0/royal-blood-royal-blood-1.epub
[Errno 2] No such file or directory: 'out_txts/royal-blood-royal-blood-1.epub'

**Comment by soskek** [comment]
How many files did the run download?
It is expected that some errors happen but they are much less than the successes.

**Comment by David-Levinthal** [comment]
about 15.6K
~/bookcorpus$ ls -l out_txts | wc
  15646  140807 1422601

so it all worked out
the error messages just were confusing..
maybe just add examples and explain the download count will vary
:-)
all is good
thanks
d

**Comment by soskek** [comment]
Thank you for the report! I added such a note on README more.
