### ISSUE TITLE
File names incorrect when epub is missing

### ISSUE THREAD

**Issue by 1227505** [soskek/bookcorpus#19]
Title says all.
I fixed it with a quick
```
            if not file_name:
                _, file_name = os.path.split(data['txt'])
```

**Comment by soskek** [comment]
Thank you for the report.
Where are these lines?

**Comment by 1227505** [comment]
download_files.py
Line 82 (after 
_, file_name = os.path.split(data['epub'])
)

**Comment by soskek** [comment]
Thanks! I'll fix it!
