### ISSUE TITLE
How to resolve URLError SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by delzac** [soskek/bookcorpus#21]
If you get the following error:

    URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>

Adding this block of code at the top of the script at `download_files.py` will resolve it.

```
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
    getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by soskek** [comment]
Thank you for the useful comment!
While it seems really useful, I don't fully understand the risk. So, I do not merge it to master for the time being and leave a decision to users.
