### ISSUE TITLE
smashwords.com forbids this; readme should tell people to get permission first

### ISSUE THREAD

**Issue by gthb** [soskek/bookcorpus#22]
The code in this repo violates both the `robots.txt` of smashwords.com:

```bash
$ curl -s https://www.smashwords.com/robots.txt | tail -4
User-agent: *
Disallow: /books/search?
Disallow: /books/download/
Crawl-delay: 4
```

and their terms of service, as far as I can see: “Third parties are not authorized to download, host and otherwise redistribute Smashwords books without prior written agreement from Smashwords” (you could _imagine_ that this only prohibits downloading for subsequent hosting or redistribution, but I think that would be an opportunistic interpretation :) ).

The readme should tell people very clearly that they must get permission from smashwords.com before running this stuff against their site.

**Comment by soskek** [comment]
Thanks! Anyway, I've added some sentences in README.
