### ISSUE TITLE
HTTPError: HTTP Error 401: Authorization Required

### ISSUE THREAD

**Issue by NotToday** [soskek/bookcorpus#8]
Thanks for you code, but I got some network trouble when I run the download_list script. The full error message is 
**Failed to open https://www.smashwords.com/books/category/1/downloads/0/free/medium/0
HTTPError: HTTP Error 401: Authorization Required**

What's more, when I use your url_list.jsonl to download file, the download_filles script gaves the same error message:
**Failed to open https://www.smashwords.com/books/download/246580/6/latest/0/0/silence.txt
HTTPError: HTTP Error 401: Authorization Required**

And I tried to open the url in my chrome, and I can see that page without error 401. Could help to find a solution? Thanks a lot~

**Comment by soskek** [comment]
Just a quick note, I haven't met the error with this repository.
Have you ever seen such errors with other scripts or tools?

**Comment by NotToday** [comment]
Never mind, I solved it by using a proxy. Should be my network problem.
